input_db:
  uri: "postgres://postgres@db/postgres?sslmode=disable"
  db_type: "postgres"
  target_schema: "pg_catalog"
output_db:
  uri: "postgres://postgres@db/postgres?sslmode=disable"
  db_type: "postgres"
  target_schema: "public"
