input_db:
  uri: "postgres://postgres:postgres@localhost:5434/postgres?sslmode=disable"
  db_type: "postgres"
  target_schema: "information_schema"
output_db:
  uri: "postgres://postgres:postgres@localhost:5434/postgres?sslmode=disable"
  db_type: "postgres"
  target_schema: "public"
