version: "3"
services:
  input_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - db-network
    restart: unless-stopped
    volumes:
      - input_db_volumen:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  output_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - db-network
    restart: unless-stopped
    volumes:
      - output_db_volumen:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes:
  input_db_volumen:
  output_db_volumen:
networks:
  db-network:
    driver: bridge
