version: "3"
services:
  input_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - input_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
  output_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - output_db:/var/lib/postgresql/data
volumes:
  input_db:
  output_db:
