# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/javier162380/go-db-transfer
    docker:
      - image: circleci/postgres:10
        environment:
          PGPORT: 5433
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run:
         name: Install dockerize
         command: |
          apt-get update
          apt-get install wget
          wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
         environment:
          DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command:  dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: go build -v
      - run: go get -v -t -d ./...
      - run: go test -race